### ISSUE TITLE
Feedback: Number Bases & Search Algorithms

### ISSUE THREAD

**Issue by anselb** [thecodingsophist/Core-Data-Structures#1]
- Nice work on you number base functions. I would've liked to have seen some comments that explain what some of the lines of code were doing as if I had wasn't familiar with number base conversion (what does line 111 do and why does it work?).
- I appreciate the work you put into your binary search functions. I encourage you to look at other students' solutions to see other ways of doing the binary search, and if you have time, figure out why your solutions do not pass the tests. In your iterative binary search, your `first` and `last` variables reference the actual items in the list rather then the indexes. While you will have to do comparisons with those items, calculating the "middle" item requires use of "left" and "right" indexes. In your recursive binary searches, I noticed a couple things there as well. Make sure you return the function (this is a possible problem whenever a recursive function is returning None), and make sure you are returning an index.

**Comment by thecodingsophist** [comment]
@anselb Thanks so much! I've fixed the problems with your help.
