### ISSUE TITLE
Feedback on Palindromes and String Searching Algorithms

### ISSUE THREAD

**Issue by fchikwekwe** [thecodingsophist/Core-Data-Structures#2]
Your palindrome implementations do not handle some pretty important edge cases: punctuation and whitespace. One way to handle this would be to check if a character is a non-letter character at every index in your string as your iterate or recurse. 

Your string searching algorithms are not passing tests. You have some infinite loop issues in your `find_all_indexes` function. You might want to double check your while condition. You are also still duplicating code throughout your function. I didn't see any time/space complexity analysis or any additional unit tests.

**Comment by thecodingsophist** [comment]
Thanks so much for your help @fchikwekwe, I've committed changes addressing edgecases, got rid of the infinite loops and included time/space complexity + additional tests.
