### ISSUE TITLE
Feedback on hash tables

### ISSUE THREAD

**Issue by fchikwekwe** [thecodingsophist/Core-Data-Structures#4]
Good start to your hash table implementation. You commented out some of your tests which are failing. You should uncomment these and run them to see what's going on. 

Your size property has some bugs. You are incrementing the size even in cases where the value is simply being updated by the set function. You need to handle cases of new keys vs cases of existing keys differently.

**Comment by thecodingsophist** [comment]
@fchikwekwe Thanks so much for looking through my code. I've un-uncommented the rest of the tests, which are now passing thanks to updating the size at the appropriate place.
